# Generated by Django 4.0.5 on 2022-07-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_db_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
